server:
  port: 9002

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: Property
    

  


logging:
  level:
    com.capg.training.propertyservice: DEBUG